Fixed Linting errors
leopardslab/nodecloud-legacy pull request #14
Opened 2017-12-20 14:43 UTC by raghavpuri

## What did you implement:

Fixed Linting errors

## How did you implement it:

changed small errors 

## How can we verify it:

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

2017-12-20 20:55 UTC, rehrumesh commented
@raghavpuri there are merge conflicts to be resolved.

2017-12-22 07:45 UTC, rehrumesh commented on examples/compute/aws-ec2.js
> +// get container object for AWS
We have a separate section for ecs. Why ec2 section has been changed?

2017-12-22 07:46 UTC, rehrumesh commented on examples/compute/aws-ec2.js
> +// get container object for AWS
@rajikaimal

2017-12-22 08:54 UTC, raghavpuri commented
Sure @rehrumesh  i'll look into it

2017-12-23 01:32 UTC, raghavpuri commented
@rehrumesh @charithccmc @agentmilindu  please review :)

2017-12-23 03:39 UTC, agentmilindu requested changes

2017-12-23 03:39 UTC, agentmilindu commented on examples/compute/aws-ecs.js
> +const nodeCloud = require("../../lib/");
According to the Airbnb Style Guide, strings should be enclosed in `'`s, not `"`s. 

I see you have done this correctly in `examples/compute/aws-ec2.js` file. I'm wondering how the Style Guide changed suddenly.

2017-12-23 04:35 UTC, raghavpuri commented
Made the changes :)

2017-12-23 04:41 UTC, agentmilindu approved these changes
LGTM

2017-12-23 04:42 UTC, agentmilindu commented
@rehrumesh @rajikaimal Please review and merge.

2017-12-23 06:00 UTC, rehrumesh approved these changes

2017-12-23 06:00 UTC, merged

2017-12-23 06:00 UTC, rehrumesh commented
Great work

2017-12-23 14:56 UTC, raghavpuri commented
Thanks!