add lint npm script
leopardslab/nodecloud-legacy pull request #24
Opened 2017-12-23 12:44 UTC by nicolasraube

## What did you implement:

Closes #23

## How did you implement it:

add new script in package.json

## How can we verify it:

Until now, the only line added is:
"lint": "eslint lib; eslint test; exit 0"
exit 0 tells npm that everything is ok even if there are lint errors.

If you now run `npm run lint`, it will lint /lib and /test.
The person who runs the command should be able to choose the linted directories / files.
This still has to be implemented.

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** NO
***Is it a breaking change?:*** NO

2017-12-23 13:05 UTC, nicolasraube commented
The only possibility I see for arguments is `npm run lint -- lib test` but then exit 0 doesn't work anymore and npm says linting failed because the exit status is 1. Any suggestions?

2017-12-24 05:06 UTC, agentmilindu requested changes

2017-12-24 05:06 UTC, agentmilindu commented on package.json
> +    "lint": "eslint lib; eslint test; exit 0"
Let's remove `exit 0`. This will result in a successful exit even if there are lint errors. 

BTW, let's not hardcode `lib` and `test`. Can't we have it like `eslint $` and then run whatever we like as `npm run lint examples`, `npm run lint lib`, etc?

2017-12-24 09:48 UTC, nicolasraube commented
@agentmilindu Changed it. I still get this error after linting.
![captura de pantalla de 2017-12-24 10-42-53](https://user-images.githubusercontent.com/19194376/34325629-49e7f5b0-e897-11e7-8dfb-ffc62ed588fe.png)
I found this issue https://github.com/eslint/eslint/issues/2409 but they can only suggest exit 0. Ugly but I guess we have to live with it.

2017-12-24 14:33 UTC, agentmilindu commented
@nicolasraube The linting fails because there are linting errors, and this is the expected behaviour. 
Anyway, good job!

2017-12-24 14:33 UTC, agentmilindu approved these changes
LGTM

2017-12-25 04:12 UTC, merged