AWS IAM support
leopardslab/nodecloud-legacy pull request #41
Opened 2018-02-28 13:04 UTC by raju249

## What did you implement:

Closes #40 

## How did you implement it:
Added AWS IAM basic functions using aws node sdk.

## How can we verify it:
Run the AWS IAM example.

## Todos:

- [x] Write tests
- [x] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

2018-02-28 15:18 UTC, rajikaimal requested changes

2018-02-28 15:18 UTC, rajikaimal commented on examples/security/aws-iam.js
> +var assert = require('assert')
can you change `var` to `const`

2018-02-28 15:57 UTC, raju249 commented
@rajikaimal 
Acknowledged changes
Please review when you have time. :smile:

2018-03-01 10:37 UTC, rajikaimal requested changes

2018-03-01 10:37 UTC, rajikaimal commented on lib/security/aws-iam.js
> +   * Create IAM Group
Can you reformat comments, some indentations are not inline with others.

2018-03-01 10:45 UTC, raju249 commented on lib/security/aws-iam.js
> +   * Create IAM Group
Sure,
Aligned the remaining comments with proper alignment.
Thanks @rajikaimal

2018-03-01 10:46 UTC, raju249 commented
Ah wait,
Some issue with my editor, they are not changed, let me add a commit with requested changes

2018-03-01 10:50 UTC, raju249 commented
@rajikaimal Did the needful.
Thanks for the changes 😄

2018-03-01 10:52 UTC, rajikaimal requested changes

2018-03-01 10:52 UTC, rajikaimal commented on examples/security/aws-iam.js
> +				iam
Let's move these into `then` block of first promise. Don't use promises within promises.

2018-03-01 10:52 UTC, rajikaimal commented on examples/security/aws-iam.js
> +						iam
Same with this promise block too.

2018-03-01 10:55 UTC, raju249 commented on examples/security/aws-iam.js
> +				iam
Actually, before attaching policy to a group, the group should be created, nodejs runs code asynchronously, due to which I need to make sure the previous step in completed.
Removing nested promises ensures this ?

2018-03-01 15:56 UTC, raju249 commented
@rajikaimanal 
Thanks a lot, now the code for example looks cleaner :smile:

2018-03-01 16:31 UTC, rajikaimal requested changes

2018-03-01 16:31 UTC, rajikaimal commented on examples/security/aws-iam.js
> +        console.log(res)
Add missing semi colon here :), this looks solid!

2018-03-01 16:32 UTC, rajikaimal commented
@raju249 no problem 😄

2018-03-01 16:32 UTC, rajikaimal commented on examples/security/aws-iam.js
> +			console.log(err);
make this `console.error`.

2018-03-01 16:33 UTC, raju249 commented
Did both the changes, anything else to include @rajikaimal 
Sorry that you had to suggest lot of changes :sweat_smile:

2018-03-01 16:39 UTC, rajikaimal commented
LGTM! @raju249 no problem, great work.

2018-03-01 16:40 UTC, rajikaimal approved these changes

2018-03-01 16:41 UTC, merged

2018-03-01 16:41 UTC, rajikaimal commented
Can you add this to documentation as well. You can refer docs folder.

2018-03-01 16:43 UTC, raju249 commented
Yeah sure @rajikaimal